steps:

# Build the 16.04 and 18.04 versions.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/exo-docker/ubuntu:18.04', '.']
  dir: '18.04'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/exo-docker/ubuntu:16.04', '.']
  dir: '16.04'

# Add more tags
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/ubuntu:18.04', 'gcr.io/$PROJECT_ID/ubuntu:18']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/ubuntu:18.04', 'gcr.io/$PROJECT_ID/ubuntu:18_latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/ubuntu:16.04', 'gcr.io/$PROJECT_ID/ubuntu:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/ubuntu:16.04', 'gcr.io/$PROJECT_ID/ubuntu:16']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/ubuntu:16.04', 'gcr.io/$PROJECT_ID/ubuntu:16_latest']

# store images
images: 
- 'gcr.io/exo-docker/ubuntu:18'
- 'gcr.io/exo-docker/ubuntu:18.04'
- 'gcr.io/exo-docker/ubuntu:18_latest'
- 'gcr.io/exo-docker/ubuntu:latest'
- 'gcr.io/exo-docker/ubuntu:16'
- 'gcr.io/exo-docker/ubuntu:16.04'
- 'gcr.io/exo-docker/ubuntu:16_latest'
